name: Telegram Auto Post

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Restore last.txt from cache
      - name: Restore last.txt
        uses: actions/cache@v4
        with:
          path: last.txt
          key: lasttxt-${{ github.run_id }}
          restore-keys: |
            lasttxt-

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install requests

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          DEST_CHANNEL: ${{ secrets.DEST_CHANNEL }}
          FEED_URL: ${{ secrets.FEED_URL }}
          FOLLOW_LINE: "ðŸ“¢ Follow @topgkguru"
        run: python bot.py

      # Save last.txt back to cache
      - name: Save last.txt
        uses: actions/cache@v4
        with:
          path: last.txt
          key: lasttxt-${{ github.run_id }}
